# Generated by Django 3.2.5 on 2021-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='paragraphe5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraphe1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle1',
            field=models.CharField(max_length=200),
        ),
    ]
